// Généré par scripts/scrutin-2026.mjs — ne pas éditer à la main.
// Source : ministère de l'Intérieur, résultats des sénatoriales 2026
// https://www.resultats-elections.interieur.gouv.fr/Senatoriales2026/nouvelle_assemblee/index.html
// (178 élus, scrutin du 27 septembre 2026)

import type { EluOfficiel } from "./senatorialesClassement";

export const ELECTION_SCRUTIN_2026 = "2026-09-27" as const;
export const ELUS_OFFICIELS_2026: EluOfficiel[] = [
  { civilite: "Mme", prenom: "Véronique", nom: "BAUDE", nom_complet: "Véronique BAUDE", departement: "Ain", liste: "L'Ain au coeur" },
  { civilite: "Mme", prenom: "Florence", nom: "BLATRIX CONTAT", nom_complet: "Florence BLATRIX CONTAT", departement: "Ain", liste: "Agir ensemble pour l'Ain et ses communes" },
  { civilite: "Mme", prenom: "Sylvie", nom: "GOY-CHAVENT", nom_complet: "Sylvie GOY-CHAVENT", departement: "Ain", liste: "Unis pour l'Ain 2026" },
  { civilite: "M.", prenom: "Antoine", nom: "LEFÈVRE", nom_complet: "Antoine LEFÈVRE", departement: "Aisne", liste: "L'AISNE AU SÉNAT" },
  { civilite: "M.", prenom: "Nicolas", nom: "FRICOTEAUX", nom_complet: "Nicolas FRICOTEAUX", departement: "Aisne", liste: "TOUS POUR L'AISNE, DES SÉNATEURS POUR TOUS" },
  { civilite: "M.", prenom: "Paul", nom: "MOUGENOT", nom_complet: "Paul MOUGENOT", departement: "Aisne", liste: "RENOUVELONS LE SENAT" },
  { civilite: "M.", prenom: "Bruno", nom: "ROJOUAN", nom_complet: "Bruno ROJOUAN", departement: "Allier", liste: "" },
  { civilite: "M.", prenom: "Claude", nom: "MALHURET", nom_complet: "Claude MALHURET", departement: "Allier", liste: "" },
  { civilite: "M.", prenom: "Jean-Yves", nom: "ROUX", nom_complet: "Jean-Yves ROUX", departement: "Alpes-de-Haute-Provence", liste: "" },
  { civilite: "M.", prenom: "Jean-Michel", nom: "ARNAUD", nom_complet: "Jean-Michel ARNAUD", departement: "Hautes-Alpes", liste: "" },
  { civilite: "M.", prenom: "Laurent", nom: "CASTILLO", nom_complet: "Laurent CASTILLO", departement: "Alpes-Maritimes", liste: "Le meilleur est à venir pour les Alpes-Maritimes" },
  { civilite: "Mme", prenom: "Gaëlle", nom: "FRONTONI", nom_complet: "Gaëlle FRONTONI", departement: "Alpes-Maritimes", liste: "Le meilleur est à venir pour les Alpes-Maritimes" },
  { civilite: "Mme", prenom: "Alexandra", nom: "BORCHIO FONTIMP", nom_complet: "Alexandra BORCHIO FONTIMP", departement: "Alpes-Maritimes", liste: "Ensemble pour les Alpes-Maritimes" },
  { civilite: "M.", prenom: "Jean-Marc", nom: "DELIA", nom_complet: "Jean-Marc DELIA", departement: "Alpes-Maritimes", liste: "Ensemble pour les Alpes-Maritimes" },
  { civilite: "Mme", prenom: "Dominique", nom: "ESTROSI-SASSONE", nom_complet: "Dominique ESTROSI-SASSONE", departement: "Alpes-Maritimes", liste: "La liberté d'agir pour les Alpes-Maritimes" },
  { civilite: "M.", prenom: "Mathieu", nom: "DARNAUD", nom_complet: "Mathieu DARNAUD", departement: "Ardèche", liste: "" },
  { civilite: "Mme", prenom: "Anne", nom: "VENTALON", nom_complet: "Anne VENTALON", departement: "Ardèche", liste: "" },
  { civilite: "Mme", prenom: "Else", nom: "JOSEPH", nom_complet: "Else JOSEPH", departement: "Ardennes", liste: "" },
  { civilite: "M.", prenom: "Marc", nom: "LAMÉNIE", nom_complet: "Marc LAMÉNIE", departement: "Ardennes", liste: "" },
  { civilite: "M.", prenom: "Jean-Jacques", nom: "MICHAU", nom_complet: "Jean-Jacques MICHAU", departement: "Ariège", liste: "" },
  { civilite: "Mme", prenom: "Valérie", nom: "BAZIN-MALGRAS", nom_complet: "Valérie BAZIN-MALGRAS", departement: "Aube", liste: "" },
  { civilite: "Mme", prenom: "Vanina", nom: "PAOLI-GAGIN", nom_complet: "Vanina PAOLI-GAGIN", departement: "Aube", liste: "" },
  { civilite: "M.", prenom: "Sébastien", nom: "PLA", nom_complet: "Sébastien PLA", departement: "Aude", liste: "" },
  { civilite: "Mme", prenom: "Claudie", nom: "FAUCON MEJEAN", nom_complet: "Claudie FAUCON MEJEAN", departement: "Aude", liste: "" },
  { civilite: "M.", prenom: "Alain", nom: "MARC", nom_complet: "Alain MARC", departement: "Aveyron", liste: "" },
  { civilite: "M.", prenom: "Jean-Claude", nom: "ANGLARS", nom_complet: "Jean-Claude ANGLARS", departement: "Aveyron", liste: "" },
  { civilite: "M.", prenom: "Jérémy", nom: "BACCHI", nom_complet: "Jérémy BACCHI", departement: "Bouches-du-Rhône", liste: "À L'ÉCOUTE DES TERRITOIRES, AU SERVICE DES COMMUNES" },
  { civilite: "Mme", prenom: "Marie-Arlette", nom: "CARLOTTI", nom_complet: "Marie-Arlette CARLOTTI", departement: "Bouches-du-Rhône", liste: "À L'ÉCOUTE DES TERRITOIRES, AU SERVICE DES COMMUNES" },
  { civilite: "M.", prenom: "Guy", nom: "BENARROCHE", nom_complet: "Guy BENARROCHE", departement: "Bouches-du-Rhône", liste: "À L'ÉCOUTE DES TERRITOIRES, AU SERVICE DES COMMUNES" },
  { civilite: "Mme", prenom: "Marie-Pierre", nom: "CALLET", nom_complet: "Marie-Pierre CALLET", departement: "Bouches-du-Rhône", liste: "AU SERVICE DES COMMUNES POUR DÉFENDRE LES BOUCHES-DU-RHÔNE" },
  { civilite: "M.", prenom: "Fabien", nom: "BRAVI", nom_complet: "Fabien BRAVI", departement: "Bouches-du-Rhône", liste: "AU SERVICE DES COMMUNES POUR DÉFENDRE LES BOUCHES-DU-RHÔNE" },
  { civilite: "Mme", prenom: "Brigitte", nom: "DEVESA", nom_complet: "Brigitte DEVESA", departement: "Bouches-du-Rhône", liste: "CAP SUR L'AVENIR DE NOS VILLES ET VILLAGES" },
  { civilite: "M.", prenom: "Renaud", nom: "MUSELIER", nom_complet: "Renaud MUSELIER", departement: "Bouches-du-Rhône", liste: "CAP SUR L'AVENIR DE NOS VILLES ET VILLAGES" },
  { civilite: "Mme", prenom: "Valérie", nom: "BOYER", nom_complet: "Valérie BOYER", departement: "Bouches-du-Rhône", liste: "UNE DROITE LIBRE ET RÉPUBLICAINE. DES MAIRES AU SERVICE DES MAIRES" },
  { civilite: "Mme", prenom: "Sonia", nom: "DE LA PROVÔTÉ", nom_complet: "Sonia DE LA PROVÔTÉ", departement: "Calvados", liste: "UNIS POUR LE CALVADOS" },
  { civilite: "M.", prenom: "François", nom: "AUBEY", nom_complet: "François AUBEY", departement: "Calvados", liste: "CALVADOS TERRES D'AVENIR" },
  { civilite: "Mme", prenom: "Corinne", nom: "FÉRET", nom_complet: "Corinne FÉRET", departement: "Calvados", liste: "Avec vous, pour le Calvados" },
  { civilite: "M.", prenom: "Bernard", nom: "DELCROS", nom_complet: "Bernard DELCROS", departement: "Cantal", liste: "" },
  { civilite: "M.", prenom: "Stéphane", nom: "SAUTAREL", nom_complet: "Stéphane SAUTAREL", departement: "Cantal", liste: "" },
  { civilite: "M.", prenom: "François", nom: "BONNEAU", nom_complet: "François BONNEAU", departement: "Charente", liste: "" },
  { civilite: "Mme", prenom: "Nicole", nom: "BONNEFOY", nom_complet: "Nicole BONNEFOY", departement: "Charente", liste: "" },
  { civilite: "Mme", prenom: "Corinne", nom: "IMBERT", nom_complet: "Corinne IMBERT", departement: "Charente-Maritime", liste: "Union pour la Charente-Maritime" },
  { civilite: "M.", prenom: "Mickaël", nom: "VALLET", nom_complet: "Mickaël VALLET", departement: "Charente-Maritime", liste: "AU COEUR DES COMMUNES" },
  { civilite: "M.", prenom: "Christophe", nom: "PLASSARD", nom_complet: "Christophe PLASSARD", departement: "Charente-Maritime", liste: "17 au Coeur" },
  { civilite: "M.", prenom: "Samir", nom: "RHIMINI", nom_complet: "Samir RHIMINI", departement: "Cher", liste: "" },
  { civilite: "M.", prenom: "Loïc", nom: "KERVRAN", nom_complet: "Loïc KERVRAN", departement: "Cher", liste: "" },
  { civilite: "M.", prenom: "Pascal", nom: "COSTE", nom_complet: "Pascal COSTE", departement: "Corrèze", liste: "" },
  { civilite: "M.", prenom: "Julien", nom: "BOUNIE", nom_complet: "Julien BOUNIE", departement: "Corrèze", liste: "" },
  { civilite: "Mme", prenom: "Anne-Catherine", nom: "LOISIER", nom_complet: "Anne-Catherine LOISIER", departement: "Côte-d'Or", liste: "ENSEMBLE, POUR LA CÔTE-D'OR DE DEMAIN !" },
  { civilite: "M.", prenom: "Alain", nom: "HOUPERT", nom_complet: "Alain HOUPERT", departement: "Côte-d'Or", liste: "ENSEMBLE, POUR LA CÔTE-D'OR DE DEMAIN !" },
  { civilite: "M.", prenom: "François", nom: "REBSAMEN", nom_complet: "François REBSAMEN", departement: "Côte-d'Or", liste: "La Voix des Communes" },
  { civilite: "Mme", prenom: "Annie", nom: "LE HOUEROU", nom_complet: "Annie LE HOUEROU", departement: "Côtes-d'Armor", liste: "Avec vous en côtes d'Armor, Pour vous au Sénat" },
  { civilite: "M.", prenom: "Gérard", nom: "LAHELLEC", nom_complet: "Gérard LAHELLEC", departement: "Côtes-d'Armor", liste: "Avec vous en côtes d'Armor, Pour vous au Sénat" },
  { civilite: "M.", prenom: "Alain", nom: "CADEC", nom_complet: "Alain CADEC", departement: "Côtes-d'Armor", liste: "Les Côtes-d'Armor au coeur" },
  { civilite: "M.", prenom: "Jean-Jacques", nom: "LOZACH", nom_complet: "Jean-Jacques LOZACH", departement: "Creuse", liste: "" },
  { civilite: "M.", prenom: "Bertrand", nom: "LABAR", nom_complet: "Bertrand LABAR", departement: "Creuse", liste: "" },
  { civilite: "M.", prenom: "Serge", nom: "MÉRILLOU", nom_complet: "Serge MÉRILLOU", departement: "Dordogne", liste: "" },
  { civilite: "Mme", prenom: "Marie-Claude", nom: "VARAILLAS", nom_complet: "Marie-Claude VARAILLAS", departement: "Dordogne", liste: "" },
  { civilite: "M.", prenom: "Jean-François", nom: "LONGEOT", nom_complet: "Jean-François LONGEOT", departement: "Doubs", liste: "BON SENS ET PROXIMITÉ" },
  { civilite: "M.", prenom: "Jacques", nom: "GROSPERRIN", nom_complet: "Jacques GROSPERRIN", departement: "Doubs", liste: "LE DOUBS AVANCE QUAND IL FAIT ÉQUIPE" },
  { civilite: "M.", prenom: "Arnaud", nom: "MARTHEY", nom_complet: "Arnaud MARTHEY", departement: "Doubs", liste: "Une voix utile, nouvelle et constructive pour le Doubs" },
  { civilite: "Mme", prenom: "Marie-Pierre", nom: "MOUTON", nom_complet: "Marie-Pierre MOUTON", departement: "Drôme", liste: "LA DRÔME ENSEMBLE" },
  { civilite: "M.", prenom: "Florent", nom: "BRUNET", nom_complet: "Florent BRUNET", departement: "Drôme", liste: "LA DRÔME ENSEMBLE" },
  { civilite: "Mme", prenom: "Nathalie", nom: "NIÉSON", nom_complet: "Nathalie NIÉSON", departement: "Drôme", liste: "SERVIR ET AGIR ENSEMBLE POUR LA DRÔME ET NOS TERRITOIRES" },
  { civilite: "M.", prenom: "Hervé", nom: "MAUREY", nom_complet: "Hervé MAUREY", departement: "Eure", liste: "UNIS POUR NOS COMMUNES ET LA RURALITÉ" },
  { civilite: "Mme", prenom: "Kristina", nom: "PLUCHET", nom_complet: "Kristina PLUCHET", departement: "Eure", liste: "UNIS POUR NOS COMMUNES ET LA RURALITÉ" },
  { civilite: "M.", prenom: "Frédéric", nom: "DUCHÉ", nom_complet: "Frédéric DUCHÉ", departement: "Eure", liste: "L'EURE DU RASSEMBLEMENT" },
  { civilite: "M.", prenom: "Albéric", nom: "DE MONTGOLFIER", nom_complet: "Albéric DE MONTGOLFIER", departement: "Eure-et-Loir", liste: "UNE ÉQUIPE POUR L'EURE-ET-LOIR : LE CHOIX DE L'EFFICACITÉ !" },
  { civilite: "Mme", prenom: "Virginie", nom: "QUENTIN", nom_complet: "Virginie QUENTIN", departement: "Eure-et-Loir", liste: "UNE ÉQUIPE POUR L'EURE-ET-LOIR : LE CHOIX DE L'EFFICACITÉ !" },
  { civilite: "M.", prenom: "Alexis", nom: "ROBIN", nom_complet: "Alexis ROBIN", departement: "Eure-et-Loir", liste: "UNE ÉQUIPE POUR L'EURE-ET-LOIR : LE CHOIX DE L'EFFICACITÉ !" },
  { civilite: "M.", prenom: "Michel", nom: "CANÉVET", nom_complet: "Michel CANÉVET", departement: "Finistère", liste: "Agissons pour le Finistère" },
  { civilite: "Mme", prenom: "Nadège", nom: "HAVET", nom_complet: "Nadège HAVET", departement: "Finistère", liste: "Agissons pour le Finistère" },
  { civilite: "Mme", prenom: "Forough", nom: "DADKHAH", nom_complet: "Forough DADKHAH", departement: "Finistère", liste: "Finistère Ensemble" },
  { civilite: "M.", prenom: "Patrick", nom: "LECLERC", nom_complet: "Patrick LECLERC", departement: "Finistère", liste: "Engagés pour le Finistère !" },
  { civilite: "M.", prenom: "Jean-Jacques", nom: "PANUNZI", nom_complet: "Jean-Jacques PANUNZI", departement: "Corse-du-Sud", liste: "" },
  { civilite: "M.", prenom: "Paul", nom: "Toussaint PARIGI", nom_complet: "Paul Toussaint PARIGI", departement: "Haute-Corse", liste: "" },
  { civilite: "M.", prenom: "Laurent", nom: "BURGOA", nom_complet: "Laurent BURGOA", departement: "Gard", liste: "Pour le Gard, tout le Gard !" },
  { civilite: "M.", prenom: "Denis", nom: "BOUAD", nom_complet: "Denis BOUAD", departement: "Gard", liste: "LE GARD EN COMMUN" },
  { civilite: "Mme", prenom: "Sylvie", nom: "JOSSERAND", nom_complet: "Sylvie JOSSERAND", departement: "Gard", liste: "AU SERVICE DES COMMUNES POUR DEFENDRE LE GARD" },
  { civilite: "M.", prenom: "Pierre", nom: "MEDEVIELLE", nom_complet: "Pierre MEDEVIELLE", departement: "Haute-Garonne", liste: "UNION RÉPUBLIQUE ET TERRITOIRES" },
  { civilite: "Mme", prenom: "Brigitte", nom: "MICOULEAU", nom_complet: "Brigitte MICOULEAU", departement: "Haute-Garonne", liste: "UNION RÉPUBLIQUE ET TERRITOIRES" },
  { civilite: "M.", prenom: "Thierry", nom: "SUAUD", nom_complet: "Thierry SUAUD", departement: "Haute-Garonne", liste: "AGIR ENSEMBLE POUR NOS COMMUNES ET NOS TERRITOIRES" },
  { civilite: "Mme", prenom: "Magali", nom: "GASTO OUSTRIC", nom_complet: "Magali GASTO OUSTRIC", departement: "Haute-Garonne", liste: "AGIR ENSEMBLE POUR NOS COMMUNES ET NOS TERRITOIRES" },
  { civilite: "M.", prenom: "Marc", nom: "PÉRÉ", nom_complet: "Marc PÉRÉ", departement: "Haute-Garonne", liste: "HAUTE-GARONNE SOCIALE, ÉCOLOGIQUE ET CITOYENNE" },
  { civilite: "M.", prenom: "Alain", nom: "DUFFOURG", nom_complet: "Alain DUFFOURG", departement: "Gers", liste: "" },
  { civilite: "Mme", prenom: "Carole", nom: "ROLANDO", nom_complet: "Carole ROLANDO", departement: "Gers", liste: "" },
  { civilite: "Mme", prenom: "Nathalie", nom: "DELATTRE", nom_complet: "Nathalie DELATTRE", departement: "Gironde", liste: "RESOLUMENT GIRONDINS" },
  { civilite: "M.", prenom: "Jacques", nom: "BREILLAT", nom_complet: "Jacques BREILLAT", departement: "Gironde", liste: "RESOLUMENT GIRONDINS" },
  { civilite: "Mme", prenom: "Géraldine", nom: "AMOUROUX", nom_complet: "Géraldine AMOUROUX", departement: "Gironde", liste: "RESOLUMENT GIRONDINS" },
  { civilite: "M.", prenom: "Hervé", nom: "GILLÉ", nom_complet: "Hervé GILLÉ", departement: "Gironde", liste: "ENGAGÉS POUR TOUTE LA GIRONDE" },
  { civilite: "Mme", prenom: "Chistine", nom: "BOST", nom_complet: "Chistine BOST", departement: "Gironde", liste: "ENGAGÉS POUR TOUTE LA GIRONDE" },
  { civilite: "Mme", prenom: "Edwige", nom: "DIAZ", nom_complet: "Edwige DIAZ", departement: "Gironde", liste: "Au service des communes pour défendre la Gironde" },
  { civilite: "M.", prenom: "Hussein", nom: "BOURGI", nom_complet: "Hussein BOURGI", departement: "Hérault", liste: "\"Pour l'Hérault! Pour la France!\"" },
  { civilite: "Mme", prenom: "Julie", nom: "FRÊCHE", nom_complet: "Julie FRÊCHE", departement: "Hérault", liste: "\"Pour l'Hérault! Pour la France!\"" },
  { civilite: "M.", prenom: "Joseph", nom: "FRANCIS", nom_complet: "Joseph FRANCIS", departement: "Hérault", liste: "Libres et engagés pour l'Hérault" },
  { civilite: "Mme", prenom: "Manon", nom: "BOUQUIN", nom_complet: "Manon BOUQUIN", departement: "Hérault", liste: "AU SERVICE DES COMMUNES POUR DÉFENDRE L'HÉRAULT" },
  { civilite: "Mme", prenom: "Françoise", nom: "GATEL", nom_complet: "Françoise GATEL", departement: "Ille-et-Vilaine", liste: "Territoire d'avenir, unis pour l'Ille-et-Vilaine" },
  { civilite: "M.", prenom: "Nicolas", nom: "BELLOIR", nom_complet: "Nicolas BELLOIR", departement: "Ille-et-Vilaine", liste: "Territoire d'avenir, unis pour l'Ille-et-Vilaine" },
  { civilite: "M.", prenom: "Daniel", nom: "SALMON", nom_complet: "Daniel SALMON", departement: "Ille-et-Vilaine", liste: "ÉCOLOGIE - SOLIDARITÉ ET TERRITOIRES" },
  { civilite: "Mme", prenom: "Sylvie", nom: "ROBERT", nom_complet: "Sylvie ROBERT", departement: "Ille-et-Vilaine", liste: "Ensemble et solidaires pour l'Ille-et-Vilaine" },
  { civilite: "Mme", prenom: "Nadine", nom: "BELLUROT", nom_complet: "Nadine BELLUROT", departement: "Indre", liste: "" },
  { civilite: "M.", prenom: "Régis", nom: "BLANCHET", nom_complet: "Régis BLANCHET", departement: "Indre", liste: "" },
  { civilite: "Mme", prenom: "Elsa", nom: "SCHALCK", nom_complet: "Elsa SCHALCK", departement: "Bas-Rhin", liste: "L'Alsace au Sénat" },
  { civilite: "M.", prenom: "Marc", nom: "SÉNÉ", nom_complet: "Marc SÉNÉ", departement: "Bas-Rhin", liste: "L'Alsace au Sénat" },
  { civilite: "Mme", prenom: "Isabelle", nom: "DOLLINGER", nom_complet: "Isabelle DOLLINGER", departement: "Bas-Rhin", liste: "L'Alsace au Sénat" },
  { civilite: "Mme", prenom: "Laurence", nom: "MULLER-BRONN", nom_complet: "Laurence MULLER-BRONN", departement: "Bas-Rhin", liste: "Une nouvelle énergie pour l'Alsace au Sénat" },
  { civilite: "Mme", prenom: "Pernelle", nom: "RICHARDOT", nom_complet: "Pernelle RICHARDOT", departement: "Bas-Rhin", liste: "L'UNION DES FORCES" },
  { civilite: "M.", prenom: "Christian", nom: "KLINGER", nom_complet: "Christian KLINGER", departement: "Haut-Rhin", liste: "Porter la passion de l'Alsace au Sénat" },
  { civilite: "Mme", prenom: "Sabine", nom: "DREXLER", nom_complet: "Sabine DREXLER", departement: "Haut-Rhin", liste: "Porter la passion de l'Alsace au Sénat" },
  { civilite: "M.", prenom: "Ludovic", nom: "HAYE", nom_complet: "Ludovic HAYE", departement: "Haut-Rhin", liste: "Avec Ludovic HAYE - Voir loin, agir près" },
  { civilite: "M.", prenom: "Benjamin", nom: "HUIN", nom_complet: "Benjamin HUIN", departement: "Haut-Rhin", liste: "L'Alsace au coeur avec Benjamin Huin" },
  { civilite: "M.", prenom: "Sébastien", nom: "MICHEL", nom_complet: "Sébastien MICHEL", departement: "Rhône", liste: "Union républicaine pour le Rhône et la Métropole" },
  { civilite: "Mme", prenom: "Catherine", nom: "DI FOLCO", nom_complet: "Catherine DI FOLCO", departement: "Rhône", liste: "Union républicaine pour le Rhône et la Métropole" },
  { civilite: "M.", prenom: "Thomas", nom: "DOSSUS", nom_complet: "Thomas DOSSUS", departement: "Rhône", liste: "Agir pour le Rhône" },
  { civilite: "M.", prenom: "Christophe", nom: "GUILLOTEAU", nom_complet: "Christophe GUILLOTEAU", departement: "Rhône", liste: "La voix des territoires - Rhône et Métropole Unis" },
  { civilite: "M.", prenom: "Bernard", nom: "FIALAIRE", nom_complet: "Bernard FIALAIRE", departement: "Rhône", liste: "Avec les élus du Rhône et de la Métropole de Lyon" },
  { civilite: "M.", prenom: "Gabriel", nom: "AMARD", nom_complet: "Gabriel AMARD", departement: "Rhône", liste: "Défendre les communes pour de bon et la République pour de vrai soutenue par la France Insoumise et Génération.s" },
  { civilite: "M.", prenom: "Serge", nom: "BERARD", nom_complet: "Serge BERARD", departement: "Rhône", liste: "Une Nouvelle Energie pour le Rhône" },
  { civilite: "M.", prenom: "Olivier", nom: "RIETMANN", nom_complet: "Olivier RIETMANN", departement: "Haute-Saône", liste: "" },
  { civilite: "M.", prenom: "Dimitri", nom: "DOUSSOT", nom_complet: "Dimitri DOUSSOT", departement: "Haute-Saône", liste: "" },
  { civilite: "M.", prenom: "Fabien", nom: "GENET", nom_complet: "Fabien GENET", departement: "Saône-et-Loire", liste: "Dynamique Saône-et-Loire avec Fabien GENET" },
  { civilite: "Mme", prenom: "Marie", nom: "MERCIER", nom_complet: "Marie MERCIER", departement: "Saône-et-Loire", liste: "AVEC VOUS POUR LA SAÔNE-ET-LOIRE" },
  { civilite: "Mme", prenom: "Paulette", nom: "MATRAY", nom_complet: "Paulette MATRAY", departement: "Saône-et-Loire", liste: "Pour une Saône-et-Loire solidaire et humaniste" },
  { civilite: "M.", prenom: "Thierry", nom: "COZIC", nom_complet: "Thierry COZIC", departement: "Sarthe", liste: "Proches des élus, engagés pour nos territoires" },
  { civilite: "M.", prenom: "Jean", nom: "Pierre VOGEL", nom_complet: "Jean Pierre VOGEL", departement: "Sarthe", liste: "La Sarthe Ensemble" },
  { civilite: "M.", prenom: "Dominique", nom: "LE MÈNER", nom_complet: "Dominique LE MÈNER", departement: "Sarthe", liste: "Ensemble pour nos Communes, pour la Sarthe et pour la France" },
  { civilite: "M.", prenom: "Cédric", nom: "VIAL", nom_complet: "Cédric VIAL", departement: "Savoie", liste: "" },
  { civilite: "Mme", prenom: "Martine", nom: "BERTHET", nom_complet: "Martine BERTHET", departement: "Savoie", liste: "" },
  { civilite: "Mme", prenom: "Sylviane", nom: "NOEL", nom_complet: "Sylviane NOEL", departement: "Haute-Savoie", liste: "Proximité et Engagement pour la Haute-Savoie" },
  { civilite: "M.", prenom: "Cyril", nom: "PELLEVAT", nom_complet: "Cyril PELLEVAT", departement: "Haute-Savoie", liste: "Proximité et Engagement pour la Haute-Savoie" },
  { civilite: "M.", prenom: "Loïc", nom: "HERVÉ", nom_complet: "Loïc HERVÉ", departement: "Haute-Savoie", liste: "Libres et indépendants pour la Haute-Savoie" },
  { civilite: "Mme", prenom: "Agnès", nom: "CANAYER", nom_complet: "Agnès CANAYER", departement: "Seine-Maritime", liste: "La Seine-Maritime, une passion commune !" },
  { civilite: "M.", prenom: "Pascal", nom: "MARTIN", nom_complet: "Pascal MARTIN", departement: "Seine-Maritime", liste: "La Seine-Maritime, une passion commune !" },
  { civilite: "Mme", prenom: "Catherine", nom: "MORIN-DESAILLY", nom_complet: "Catherine MORIN-DESAILLY", departement: "Seine-Maritime", liste: "La Seine-Maritime, une passion commune !" },
  { civilite: "M.", prenom: "Bastien", nom: "CORITON", nom_complet: "Bastien CORITON", departement: "Seine-Maritime", liste: "NOS COMMUNES, notre avenir" },
  { civilite: "Mme", prenom: "Céline", nom: "BRULIN", nom_complet: "Céline BRULIN", departement: "Seine-Maritime", liste: "Avec CÉLINE BRULIN, mettons la commune au coeur de la République" },
  { civilite: "M.", prenom: "Léon", nom: "LEVASSEUR", nom_complet: "Léon LEVASSEUR", departement: "Seine-Maritime", liste: "AU SERVICE DES COMMUNES POUR DÉFENDRE LA SEINE-MARITIME" },
  { civilite: "M.", prenom: "Philippe", nom: "MOUILLER", nom_complet: "Philippe MOUILLER", departement: "Deux-Sèvres", liste: "" },
  { civilite: "Mme", prenom: "Marie-Pierre", nom: "MISSIOUX", nom_complet: "Marie-Pierre MISSIOUX", departement: "Deux-Sèvres", liste: "" },
  { civilite: "M.", prenom: "Stéphane", nom: "DEMILLY", nom_complet: "Stéphane DEMILLY", departement: "Somme", liste: "Avec Stéphane DEMILLY, une Somme d'énergies !" },
  { civilite: "M.", prenom: "Rémi", nom: "CARDON", nom_complet: "Rémi CARDON", departement: "Somme", liste: "La SOMME a de L'AVENIR" },
  { civilite: "M.", prenom: "Laurent", nom: "SOMON", nom_complet: "Laurent SOMON", departement: "Somme", liste: "AVEC VOUS ! POUR VOUS !" },
  { civilite: "Mme", prenom: "Marie-Lise", nom: "HOUSSEAU", nom_complet: "Marie-Lise HOUSSEAU", departement: "Tarn", liste: "" },
  { civilite: "M.", prenom: "Philippe", nom: "FOLLIOT", nom_complet: "Philippe FOLLIOT", departement: "Tarn", liste: "" },
  { civilite: "M.", prenom: "Pierre-Antoine", nom: "LEVI", nom_complet: "Pierre-Antoine LEVI", departement: "Tarn-et-Garonne", liste: "" },
  { civilite: "M.", prenom: "François", nom: "BONHOMME", nom_complet: "François BONHOMME", departement: "Tarn-et-Garonne", liste: "" },
  { civilite: "Mme", prenom: "Françoise", nom: "DUMONT", nom_complet: "Françoise DUMONT", departement: "Var", liste: "Unis pour l'Avenir de nos Communes et du Var" },
  { civilite: "M.", prenom: "Christian", nom: "SIMON", nom_complet: "Christian SIMON", departement: "Var", liste: "Unis pour l'Avenir de nos Communes et du Var" },
  { civilite: "M.", prenom: "Frank", nom: "GILETTI", nom_complet: "Frank GILETTI", departement: "Var", liste: "AU SERVICE DES COMMUNES POUR DEFENDRE LE VAR" },
  { civilite: "Mme", prenom: "Carine", nom: "LEROY", nom_complet: "Carine LEROY", departement: "Var", liste: "AU SERVICE DES COMMUNES POUR DEFENDRE LE VAR" },
  { civilite: "M.", prenom: "Jean-Baptiste", nom: "BLANC", nom_complet: "Jean-Baptiste BLANC", departement: "Vaucluse", liste: "Le Vaucluse 2032 avec Jean-Baptiste Blanc" },
  { civilite: "Mme", prenom: "Dominique", nom: "SANTONI", nom_complet: "Dominique SANTONI", departement: "Vaucluse", liste: "Le Vaucluse 2032 avec Jean-Baptiste Blanc" },
  { civilite: "M.", prenom: "Thierry", nom: "D'AIGREMONT", nom_complet: "Thierry D'AIGREMONT", departement: "Vaucluse", liste: "Au service des communes, pour défendre le Vaucluse" },
  { civilite: "M.", prenom: "Bruno", nom: "RETAILLEAU", nom_complet: "Bruno RETAILLEAU", departement: "Vendée", liste: "Union pour la Vendée" },
  { civilite: "Mme", prenom: "Annick", nom: "BILLON", nom_complet: "Annick BILLON", departement: "Vendée", liste: "Union pour la Vendée" },
  { civilite: "M.", prenom: "Maxence", nom: "DE RUGY", nom_complet: "Maxence DE RUGY", departement: "Vendée", liste: "Union pour la Vendée" },
  { civilite: "M.", prenom: "Bruno", nom: "BELIN", nom_complet: "Bruno BELIN", departement: "Vienne", liste: "" },
  { civilite: "Mme", prenom: "Marie-Jeanne", nom: "BELLAMY", nom_complet: "Marie-Jeanne BELLAMY", departement: "Vienne", liste: "" },
  { civilite: "Mme", prenom: "Isabelle", nom: "BRIQUET", nom_complet: "Isabelle BRIQUET", departement: "Haute-Vienne", liste: "" },
  { civilite: "M.", prenom: "Christian", nom: "REDON-SARRAZY", nom_complet: "Christian REDON-SARRAZY", departement: "Haute-Vienne", liste: "" },
  { civilite: "M.", prenom: "Daniel", nom: "GREMILLET", nom_complet: "Daniel GREMILLET", departement: "Vosges", liste: "" },
  { civilite: "M.", prenom: "Jean", nom: "HINGRAY", nom_complet: "Jean HINGRAY", departement: "Vosges", liste: "" },
  { civilite: "M.", prenom: "Jean-Baptiste", nom: "LEMOYNE", nom_complet: "Jean-Baptiste LEMOYNE", departement: "Yonne", liste: "" },
  { civilite: "Mme", prenom: "Dominique", nom: "VERIEN", nom_complet: "Dominique VERIEN", departement: "Yonne", liste: "" },
  { civilite: "M.", prenom: "Cédric", nom: "PERRIN", nom_complet: "Cédric PERRIN", departement: "Territoire de Belfort", liste: "" },
  { civilite: "M.", prenom: "Rodolphe", nom: "ALEXANDRE", nom_complet: "Rodolphe ALEXANDRE", departement: "Guyane", liste: "" },
  { civilite: "M.", prenom: "Ryan", nom: "PERSAUD", nom_complet: "Ryan PERSAUD", departement: "Guyane", liste: "" },
  { civilite: "Mme", prenom: "Micheline", nom: "JACQUES", nom_complet: "Micheline JACQUES", departement: "Saint-Barthélemy", liste: "" },
  { civilite: "M.", prenom: "Daniel", nom: "GIBBS", nom_complet: "Daniel GIBBS", departement: "Saint-Martin", liste: "" },
  { civilite: "M.", prenom: "Lafaele", nom: "TUKUMULI", nom_complet: "Lafaele TUKUMULI", departement: "Wallis et Futuna", liste: "" },
  { civilite: "Mme", prenom: "Lana", nom: "TETUANUI", nom_complet: "Lana TETUANUI", departement: "Polynésie française", liste: "" },
  { civilite: "M.", prenom: "Edouard", nom: "FRITCH", nom_complet: "Edouard FRITCH", departement: "Polynésie française", liste: "" },
  { civilite: "Mme", prenom: "Sophie", nom: "BRIANTE-GUILLEMONT", nom_complet: "Sophie BRIANTE-GUILLEMONT", departement: "Français établis hors de France", liste: "ASFE 2026 - La Voix des Français de l'étranger" },
  { civilite: "Mme", prenom: "Mélanie", nom: "VOGEL", nom_complet: "Mélanie VOGEL", departement: "Français établis hors de France", liste: "Rassemblement écologiste et solidaire pour les Français.es de l'étranger" },
  { civilite: "M.", prenom: "Yan", nom: "CHANTREL", nom_complet: "Yan CHANTREL", departement: "Français établis hors de France", liste: "JUSTICE ET SOLIDARITE POUR LES FRANCAIS DANS LE MONDE" },
  { civilite: "M.", prenom: "Olivier", nom: "CADIC", nom_complet: "Olivier CADIC", departement: "Français établis hors de France", liste: "Libres et Indépendants" },
  { civilite: "M.", prenom: "Bertrand", nom: "DUPONT", nom_complet: "Bertrand DUPONT", departement: "Français établis hors de France", liste: "Français à part entière - Union de la droite, du centre et des indépendants pour les Français de l'étranger" },
  { civilite: "Mme", prenom: "Marie", nom: "Ange ROUSSELOT", nom_complet: "Marie Ange ROUSSELOT", departement: "Français établis hors de France", liste: "À vos côtés, partout dans le monde" },
];
